// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AmableQuishpePromBurgers.Migrations
{
    [DbContext(typeof(AmableQuishpePromBurgersContext))]
    partial class AmableQuishpePromBurgersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AmableQuishpePromBurgers.Models.Burger", b =>
                {
                    b.Property<int>("Burgerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Burgerid"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Withcheese")
                        .HasColumnType("bit");

                    b.HasKey("Burgerid");

                    b.ToTable("Burger");
                });

            modelBuilder.Entity("AmableQuishpePromBurgers.Models.Promo", b =>
                {
                    b.Property<int>("Promoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Promoid"));

                    b.Property<int>("Burgerid")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPromo")
                        .HasColumnType("datetime2");

                    b.HasKey("Promoid");

                    b.HasIndex("Burgerid");

                    b.ToTable("Promo");
                });

            modelBuilder.Entity("AmableQuishpePromBurgers.Models.Promo", b =>
                {
                    b.HasOne("AmableQuishpePromBurgers.Models.Burger", "Burger")
                        .WithMany("Promos")
                        .HasForeignKey("Burgerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Burger");
                });

            modelBuilder.Entity("AmableQuishpePromBurgers.Models.Burger", b =>
                {
                    b.Navigation("Promos");
                });
#pragma warning restore 612, 618
        }
    }
}
